name: "Test Example Pipeline"
env:
  REGION: "uk"
  IS_BUILDKITE: ${BUILDKITE}
  BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
  GIT_PULL_REQUEST: ${BUILDKITE_PULL_REQUEST}
  PULL_REQUEST_BASE_BRANCH: ${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
  GIT_COMMIT: ${BUILDKITE_COMMIT}
  GIT_BRANCH: ${BUILDKITE_BRANCH} 

steps:
  - input: "Information please"
    fields:
      - text: "What is the date today?"
        key: "todays-date"
  - label: "Do Stuff"
    command: script.sh