name: "Test Buildkite example repo"
env:
  IS_BUILDKITE: ${BUILDKITE}
  BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
  GIT_PULL_REQUEST: ${BUILDKITE_PULL_REQUEST}
  PULL_REQUEST_BASE_BRANCH: ${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
  GIT_COMMIT: ${BUILDKITE_COMMIT}
  GIT_BRANCH: ${BUILDKITE_BRANCH}
  AWS_DEFAULT_REGION: eu-west-1
steps:
  - label: ":gb: tf validate :terraform:"
    key: "validate-terraform"
    command: .buildkite/scripts/validate-terraform.sh
    agents:
      queue: butlins-dev-agent
  
  - label: ":flag-gb: terraform: static analysis: :aws-lambda:"
    key: "checkov"
    command: .buildkite/scripts/static-analysis.sh
    soft_fail:
    - exit_status: 2
    env:
      ENV: development
    agents:
      queue: butlins-dev-agent

  - wait

  - label: ":gb: dev build & apply :terraform:"
    depends_on:
      - "validate-terraform"
    command: .buildkite/scripts/placeholder.sh
    env:
      ENV: development
    if: build.branch == pipeline.default_branch
    agents:
      queue: butlins-dev-agent

  - input: ":gb: deploy to qa? :thumbsup:"
    key: "block-qa"
    if: build.branch == pipeline.default_branch
    prompt: "Confirm deployment to QA?"

  - label: ":gb: qa build & apply :terraform:"
    depends_on:
      - "block-qa"
      - "validate-terraform"
    command: .buildkite/scripts/placeholder.sh
    env:
      ENV: uat
    if: build.branch == pipeline.default_branch
    agents:
      queue: butlins-qa-agent

  - input: ":gb: deploy to production? :thumbsup:"
    key: "block-production"
    if: build.branch == pipeline.default_branch
    prompt: "Confirm deployment to Production?"

  - label: ":gb: prod build & apply :terraform:"
    depends_on:
      - "block-production"
      - "validate-terraform"
    command: .buildkite/scripts/placeholder.sh
    env:
      ENV: production
    if: build.branch == pipeline.default_branch
    agents:
      queue: butlins-prod-agent

